services:
  notification-service:
    container_name: notification-service
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000

  db:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
